/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_v1_categories_get"];
        put?: never;
        /** Create Categories */
        post: operations["create_categories_api_v1_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Categories */
        put: operations["update_categories_api_v1_categories__item_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Brands */
        get: operations["list_brands_api_v1_brands_get"];
        put?: never;
        /** Create Brands */
        post: operations["create_brands_api_v1_brands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brands/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Brands */
        put: operations["update_brands_api_v1_brands__item_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suppliers */
        get: operations["list_suppliers_api_v1_suppliers_get"];
        put?: never;
        /** Create Suppliers */
        post: operations["create_suppliers_api_v1_suppliers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Suppliers */
        put: operations["update_suppliers_api_v1_suppliers__item_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_v1_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_v1_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_api_v1_products__product_id__patch"];
        trace?: never;
    };
    "/api/v1/products/{product_id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Variants */
        post: operations["add_variants_api_v1_products__product_id__variants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variants/{variant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Variant */
        patch: operations["update_variant_api_v1_variants__variant_id__patch"];
        trace?: never;
    };
    "/api/v1/variants/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup Variants
         * @description POS search: exact barcode/SKU match first, otherwise name/SKU search.
         */
        get: operations["lookup_variants_api_v1_variants_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Products */
        post: operations["import_products_api_v1_products_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/import/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import Template */
        get: operations["import_template_api_v1_products_import_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variants/labels.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Barcode Labels */
        post: operations["barcode_labels_api_v1_variants_labels_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Levels */
        get: operations["stock_levels_api_v1_inventory_stock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Receipts */
        get: operations["list_receipts_api_v1_inventory_receipts_get"];
        put?: never;
        /** Create Receipt */
        post: operations["create_receipt_api_v1_inventory_receipts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/receipts/{receipt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Receipt */
        get: operations["get_receipt_api_v1_inventory_receipts__receipt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Adjustment */
        post: operations["create_adjustment_api_v1_inventory_adjustments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Movements */
        get: operations["list_movements_api_v1_inventory_movements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Customers */
        get: operations["search_customers_api_v1_customers_get"];
        put?: never;
        /** Create Customer */
        post: operations["create_customer_api_v1_customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/by-phone/{phone}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Phone */
        get: operations["get_by_phone_api_v1_customers_by_phone__phone__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Customer */
        put: operations["update_customer_api_v1_customers__customer_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quote */
        post: operations["quote_api_v1_sales_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sales */
        get: operations["list_sales_api_v1_sales_get"];
        put?: never;
        /** Create Sale */
        post: operations["create_sale_api_v1_sales_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/{sale_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sale */
        get: operations["get_sale_api_v1_sales__sale_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/{sale_id}/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Return */
        post: operations["create_return_api_v1_sales__sale_id__returns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/{sale_id}/invoice.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invoice Pdf */
        get: operations["invoice_pdf_api_v1_sales__sale_id__invoice_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/{sale_id}/invoice.html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invoice Html */
        get: operations["invoice_html_api_v1_sales__sale_id__invoice_html_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/returns/{return_id}/credit-note.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Credit Note Pdf */
        get: operations["credit_note_pdf_api_v1_returns__return_id__credit_note_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_reports_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sales */
        get: operations["sales_api_v1_reports_sales_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products */
        get: operations["products_api_v1_reports_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/stock-valuation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Valuation */
        get: operations["stock_valuation_api_v1_reports_stock_valuation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/low-stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Low Stock */
        get: operations["low_stock_api_v1_reports_low_stock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/gst": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gst Summary */
        get: operations["gst_summary_api_v1_reports_gst_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/profit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profit */
        get: operations["profit_api_v1_reports_profit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Store */
        get: operations["get_store_api_v1_settings_store_get"];
        /** Update Store */
        put: operations["update_store_api_v1_settings_store_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/tax-slabs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tax Slabs */
        get: operations["list_tax_slabs_api_v1_settings_tax_slabs_get"];
        put?: never;
        /** Create Tax Slab */
        post: operations["create_tax_slab_api_v1_settings_tax_slabs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/tax-slabs/{slab_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Tax Slab */
        put: operations["update_tax_slab_api_v1_settings_tax_slabs__slab_id__put"];
        post?: never;
        /** Delete Tax Slab */
        delete: operations["delete_tax_slab_api_v1_settings_tax_slabs__slab_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustmentIn */
        AdjustmentIn: {
            /** Variant Id */
            variant_id: number;
            /** Qty Delta */
            qty_delta: number;
            /** Reason */
            reason: string;
        };
        /** Body_add_variants_api_v1_products__product_id__variants_post */
        Body_add_variants_api_v1_products__product_id__variants_post: {
            variant?: components["schemas"]["VariantCreate"] | null;
            matrix?: components["schemas"]["VariantMatrix"] | null;
        };
        /** Body_import_products_api_v1_products_import_post */
        Body_import_products_api_v1_products_import_post: {
            /** File */
            file: string;
        };
        /** BrandIn */
        BrandIn: {
            /** Name */
            name: string;
        };
        /** BrandOut */
        BrandOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** CategoryIn */
        CategoryIn: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
        };
        /** CustomerIn */
        CustomerIn: {
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Email */
            email?: string | null;
            /** Gstin */
            gstin?: string | null;
            /** State Code */
            state_code?: string | null;
            /** Address */
            address?: string | null;
        };
        /** CustomerOut */
        CustomerOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string | null;
            /** Gstin */
            gstin: string | null;
            /** State Code */
            state_code: string | null;
            /** Address */
            address: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResult */
        ImportResult: {
            /** Products Created */
            products_created: number;
            /** Variants Created */
            variants_created: number;
            /** Errors */
            errors: string[];
        };
        /** LabelRequest */
        LabelRequest: {
            /** Variant Id */
            variant_id: number;
            /**
             * Copies
             * @default 1
             */
            copies: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MovementOut */
        MovementOut: {
            /** Id */
            id: number;
            /** Variant Id */
            variant_id: number;
            /** Sku */
            sku: string;
            /** Product Name */
            product_name: string;
            /** Qty Delta */
            qty_delta: number;
            type: components["schemas"]["MovementType"];
            /** Ref Type */
            ref_type: string | null;
            /** Ref Id */
            ref_id: number | null;
            /** Reason */
            reason: string | null;
            /** User Name */
            user_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MovementType
         * @enum {string}
         */
        MovementType: "purchase" | "sale" | "return" | "adjustment";
        /** Page[MovementOut] */
        Page_MovementOut_: {
            /** Items */
            items: components["schemas"]["MovementOut"][];
            /** Total */
            total: number;
        };
        /** Page[ProductOut] */
        Page_ProductOut_: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Total */
            total: number;
        };
        /** Page[ReceiptOut] */
        Page_ReceiptOut_: {
            /** Items */
            items: components["schemas"]["ReceiptOut"][];
            /** Total */
            total: number;
        };
        /** Page[SaleSummary] */
        Page_SaleSummary_: {
            /** Items */
            items: components["schemas"]["SaleSummary"][];
            /** Total */
            total: number;
        };
        /** Page[StockLevel] */
        Page_StockLevel_: {
            /** Items */
            items: components["schemas"]["StockLevel"][];
            /** Total */
            total: number;
        };
        /** PaymentIn */
        PaymentIn: {
            method: components["schemas"]["PaymentMethod"];
            /** Amount */
            amount: number | string;
            /** Reference */
            reference?: string | null;
        };
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "cash" | "card" | "upi";
        /** PaymentOut */
        PaymentOut: {
            method: components["schemas"]["PaymentMethod"];
            /** Amount */
            amount: string;
            /** Reference */
            reference: string | null;
        };
        /** ProductCreate */
        ProductCreate: {
            /** Name */
            name: string;
            /** Category Id */
            category_id?: number | null;
            /** Brand Id */
            brand_id?: number | null;
            /** Description */
            description?: string | null;
            /** Hsn Code */
            hsn_code: string;
            /** Gender */
            gender?: string | null;
            /** Material */
            material?: string | null;
            /**
             * Variants
             * @default []
             */
            variants: components["schemas"]["VariantCreate"][];
            matrix?: components["schemas"]["VariantMatrix"] | null;
        };
        /** ProductOut */
        ProductOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category Id */
            category_id: number | null;
            /** Brand Id */
            brand_id: number | null;
            category: components["schemas"]["CategoryOut"] | null;
            brand: components["schemas"]["BrandOut"] | null;
            /** Description */
            description: string | null;
            /** Hsn Code */
            hsn_code: string;
            /** Gender */
            gender: string | null;
            /** Material */
            material: string | null;
            /** Is Active */
            is_active: boolean;
            /** Variants */
            variants: components["schemas"]["VariantOut"][];
        };
        /** ProductUpdate */
        ProductUpdate: {
            /** Name */
            name?: string | null;
            /** Category Id */
            category_id?: number | null;
            /** Brand Id */
            brand_id?: number | null;
            /** Description */
            description?: string | null;
            /** Hsn Code */
            hsn_code?: string | null;
            /** Gender */
            gender?: string | null;
            /** Material */
            material?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** QuoteOut */
        QuoteOut: {
            /** Subtotal */
            subtotal: string;
            /** Discount */
            discount: string;
            /** Taxable Value */
            taxable_value: string;
            /** Cgst */
            cgst: string;
            /** Sgst */
            sgst: string;
            /** Igst */
            igst: string;
            /** Round Off */
            round_off: string;
            /** Grand Total */
            grand_total: string;
            /** Items */
            items: components["schemas"]["SaleItemOut"][];
        };
        /** ReceiptCreate */
        ReceiptCreate: {
            /** Supplier Id */
            supplier_id?: number | null;
            /** Invoice Ref */
            invoice_ref?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Update Cost Price
             * @default true
             */
            update_cost_price: boolean;
            /** Items */
            items: components["schemas"]["ReceiptItemIn"][];
        };
        /** ReceiptItemIn */
        ReceiptItemIn: {
            /** Variant Id */
            variant_id: number;
            /** Qty */
            qty: number;
            /** Unit Cost */
            unit_cost?: number | string | null;
        };
        /** ReceiptItemOut */
        ReceiptItemOut: {
            /** Id */
            id: number;
            /** Variant Id */
            variant_id: number;
            /** Qty */
            qty: number;
            /** Unit Cost */
            unit_cost: string;
            /** Sku */
            sku: string;
            /** Product Name */
            product_name: string;
            /** Size */
            size: string;
            /** Color */
            color: string;
        };
        /** ReceiptOut */
        ReceiptOut: {
            /** Id */
            id: number;
            /** Supplier Id */
            supplier_id: number | null;
            /** Supplier Name */
            supplier_name: string | null;
            /** Invoice Ref */
            invoice_ref: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Created By Name */
            created_by_name: string;
            /** Total Qty */
            total_qty: number;
            /** Total Cost */
            total_cost: string;
            /** Items */
            items: components["schemas"]["ReceiptItemOut"][];
        };
        /** ReturnCreate */
        ReturnCreate: {
            /** Items */
            items: components["schemas"]["ReturnItemIn"][];
            /** Reason */
            reason?: string | null;
        };
        /** ReturnItemIn */
        ReturnItemIn: {
            /** Sale Item Id */
            sale_item_id: number;
            /** Qty */
            qty: number;
            /**
             * Restock
             * @default true
             */
            restock: boolean;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "cashier";
        /** SaleCreate */
        SaleCreate: {
            /** Items */
            items: components["schemas"]["SaleItemIn"][];
            /** Payments */
            payments: components["schemas"]["PaymentIn"][];
            /** Customer Id */
            customer_id?: number | null;
            /**
             * Bill Discount
             * @default 0
             */
            bill_discount: number | string;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** SaleItemIn */
        SaleItemIn: {
            /** Variant Id */
            variant_id: number;
            /** Qty */
            qty: number;
            /**
             * Discount
             * @default 0
             */
            discount: number | string;
        };
        /** SaleItemOut */
        SaleItemOut: {
            /** Id */
            id: number;
            /** Variant Id */
            variant_id: number;
            /** Product Name */
            product_name: string;
            /** Sku */
            sku: string;
            /** Size */
            size: string;
            /** Color */
            color: string;
            /** Hsn Code */
            hsn_code: string;
            /** Qty */
            qty: number;
            /** Returned Qty */
            returned_qty: number;
            /** Unit Price */
            unit_price: string;
            /** Discount */
            discount: string;
            /** Taxable Value */
            taxable_value: string;
            /** Gst Rate */
            gst_rate: string;
            /** Cgst */
            cgst: string;
            /** Sgst */
            sgst: string;
            /** Igst */
            igst: string;
            /** Line Total */
            line_total: string;
        };
        /** SaleOut */
        SaleOut: {
            /** Id */
            id: number;
            /** Invoice No */
            invoice_no: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            customer: components["schemas"]["CustomerOut"] | null;
            /** Cashier Name */
            cashier_name: string;
            /** Place Of Supply */
            place_of_supply: string;
            /** Subtotal */
            subtotal: string;
            /** Discount */
            discount: string;
            /** Taxable Value */
            taxable_value: string;
            /** Cgst */
            cgst: string;
            /** Sgst */
            sgst: string;
            /** Igst */
            igst: string;
            /** Round Off */
            round_off: string;
            /** Grand Total */
            grand_total: string;
            status: components["schemas"]["SaleStatus"];
            /** Notes */
            notes: string | null;
            /** Items */
            items: components["schemas"]["SaleItemOut"][];
            /** Payments */
            payments: components["schemas"]["PaymentOut"][];
            /** Returns */
            returns: components["schemas"]["SaleReturnOut"][];
        };
        /**
         * SaleQuote
         * @description Totals preview for the POS cart (no stock or payments changed).
         */
        SaleQuote: {
            /** Items */
            items: components["schemas"]["SaleItemIn"][];
            /** Customer Id */
            customer_id?: number | null;
            /**
             * Bill Discount
             * @default 0
             */
            bill_discount: number | string;
        };
        /** SaleReturnItemOut */
        SaleReturnItemOut: {
            /** Sale Item Id */
            sale_item_id: number;
            /** Qty */
            qty: number;
            /** Restock */
            restock: boolean;
            /** Amount */
            amount: string;
        };
        /** SaleReturnOut */
        SaleReturnOut: {
            /** Id */
            id: number;
            /** Credit Note No */
            credit_note_no: string;
            /** Sale Id */
            sale_id: number;
            /** Taxable Value */
            taxable_value: string;
            /** Cgst */
            cgst: string;
            /** Sgst */
            sgst: string;
            /** Igst */
            igst: string;
            /** Refund Amount */
            refund_amount: string;
            /** Reason */
            reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Items */
            items: components["schemas"]["SaleReturnItemOut"][];
        };
        /**
         * SaleStatus
         * @enum {string}
         */
        SaleStatus: "completed" | "partially_returned" | "returned";
        /** SaleSummary */
        SaleSummary: {
            /** Id */
            id: number;
            /** Invoice No */
            invoice_no: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Name */
            customer_name: string | null;
            /** Cashier Name */
            cashier_name: string;
            /** Grand Total */
            grand_total: string;
            status: components["schemas"]["SaleStatus"];
            /** Item Count */
            item_count: number;
        };
        /** StockLevel */
        StockLevel: {
            /** Variant Id */
            variant_id: number;
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Category */
            category: string | null;
            /** Brand */
            brand: string | null;
            /** Sku */
            sku: string;
            /** Barcode */
            barcode: string;
            /** Size */
            size: string;
            /** Color */
            color: string;
            /** Quantity On Hand */
            quantity_on_hand: number;
            /** Reorder Level */
            reorder_level: number;
            /** Cost Price */
            cost_price: string;
            /** Selling Price */
            selling_price: string;
            /** Low Stock */
            low_stock: boolean;
        };
        /** StoreSettingsIn */
        StoreSettingsIn: {
            /** Name */
            name: string;
            /**
             * Address
             * @default
             */
            address: string;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Gstin */
            gstin?: string | null;
            /** State Code */
            state_code: string;
            /** State Name */
            state_name: string;
            /** Invoice Prefix */
            invoice_prefix: string;
            /** Credit Note Prefix */
            credit_note_prefix: string;
            /** Footer Terms */
            footer_terms?: string | null;
        };
        /** StoreSettingsOut */
        StoreSettingsOut: {
            /** Name */
            name: string;
            /**
             * Address
             * @default
             */
            address: string;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Gstin */
            gstin?: string | null;
            /** State Code */
            state_code: string;
            /** State Name */
            state_name: string;
            /** Invoice Prefix */
            invoice_prefix: string;
            /** Credit Note Prefix */
            credit_note_prefix: string;
            /** Footer Terms */
            footer_terms?: string | null;
        };
        /** SupplierIn */
        SupplierIn: {
            /** Name */
            name: string;
            /** Gstin */
            gstin?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
        };
        /** SupplierOut */
        SupplierOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Gstin */
            gstin: string | null;
            /** Phone */
            phone: string | null;
            /** Address */
            address: string | null;
        };
        /** TaxSlabIn */
        TaxSlabIn: {
            /** Name */
            name: string;
            /**
             * Hsn Prefix
             * @default
             */
            hsn_prefix: string;
            /** Price Threshold */
            price_threshold?: number | string | null;
            /** Rate Below */
            rate_below: number | string;
            /** Rate Above */
            rate_above: number | string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
        };
        /** TaxSlabOut */
        TaxSlabOut: {
            /** Name */
            name: string;
            /**
             * Hsn Prefix
             * @default
             */
            hsn_prefix: string;
            /** Price Threshold */
            price_threshold?: string | null;
            /** Rate Below */
            rate_below: string;
            /** Rate Above */
            rate_above: string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Id */
            id: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
            /** @default cashier */
            role: components["schemas"]["Role"];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /** Is Active */
            is_active: boolean;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Password */
            password?: string | null;
            role?: components["schemas"]["Role"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariantCreate */
        VariantCreate: {
            /** Size */
            size: string;
            /** Color */
            color: string;
            /** Mrp */
            mrp: number | string;
            /** Selling Price */
            selling_price: number | string;
            /** Cost Price */
            cost_price: number | string;
            /**
             * Reorder Level
             * @default 5
             */
            reorder_level: number;
            /** Sku */
            sku?: string | null;
            /** Barcode */
            barcode?: string | null;
        };
        /**
         * VariantLookup
         * @description Variant with its product's name, for POS search results.
         */
        VariantLookup: {
            /** Id */
            id: number;
            /** Product Id */
            product_id: number;
            /** Sku */
            sku: string;
            /** Barcode */
            barcode: string;
            /** Size */
            size: string;
            /** Color */
            color: string;
            /** Mrp */
            mrp: string;
            /** Selling Price */
            selling_price: string;
            /** Cost Price */
            cost_price: string;
            /** Reorder Level */
            reorder_level: number;
            /** Quantity On Hand */
            quantity_on_hand: number;
            /** Is Active */
            is_active: boolean;
            /** Product Name */
            product_name: string;
            /** Hsn Code */
            hsn_code: string;
        };
        /**
         * VariantMatrix
         * @description Generate one variant per size x color, all at the same prices.
         */
        VariantMatrix: {
            /** Sizes */
            sizes: string[];
            /** Colors */
            colors: string[];
            /** Mrp */
            mrp: number | string;
            /** Selling Price */
            selling_price: number | string;
            /** Cost Price */
            cost_price: number | string;
            /**
             * Reorder Level
             * @default 5
             */
            reorder_level: number;
        };
        /** VariantOut */
        VariantOut: {
            /** Id */
            id: number;
            /** Product Id */
            product_id: number;
            /** Sku */
            sku: string;
            /** Barcode */
            barcode: string;
            /** Size */
            size: string;
            /** Color */
            color: string;
            /** Mrp */
            mrp: string;
            /** Selling Price */
            selling_price: string;
            /** Cost Price */
            cost_price: string;
            /** Reorder Level */
            reorder_level: number;
            /** Quantity On Hand */
            quantity_on_hand: number;
            /** Is Active */
            is_active: boolean;
        };
        /** VariantUpdate */
        VariantUpdate: {
            /** Mrp */
            mrp?: number | string | null;
            /** Selling Price */
            selling_price?: number | string | null;
            /** Cost Price */
            cost_price?: number | string | null;
            /** Reorder Level */
            reorder_level?: number | null;
            /** Barcode */
            barcode?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ims_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    create_categories_api_v1_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_categories_api_v1_categories__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_brands_api_v1_brands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandOut"][];
                };
            };
        };
    };
    create_brands_api_v1_brands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_brands_api_v1_brands__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suppliers_api_v1_suppliers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"][];
                };
            };
        };
    };
    create_suppliers_api_v1_suppliers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_suppliers_api_v1_suppliers__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_v1_products_get: {
        parameters: {
            query?: {
                q?: string | null;
                category_id?: number | null;
                brand_id?: number | null;
                include_inactive?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProductOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_v1_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_v1_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_variants_api_v1_products__product_id__variants_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_add_variants_api_v1_products__product_id__variants_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_variant_api_v1_variants__variant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_variants_api_v1_variants_lookup_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantLookup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_products_api_v1_products_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_products_api_v1_products_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_template_api_v1_products_import_template_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    barcode_labels_api_v1_variants_labels_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelRequest"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_levels_api_v1_inventory_stock_get: {
        parameters: {
            query?: {
                q?: string | null;
                category_id?: number | null;
                brand_id?: number | null;
                size?: string | null;
                color?: string | null;
                low_stock_only?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StockLevel_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_receipts_api_v1_inventory_receipts_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReceiptOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_receipt_api_v1_inventory_receipts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_receipt_api_v1_inventory_receipts__receipt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_adjustment_api_v1_inventory_adjustments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustmentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_movements_api_v1_inventory_movements_get: {
        parameters: {
            query?: {
                variant_id?: number | null;
                type?: components["schemas"]["MovementType"] | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MovementOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_customers_api_v1_customers_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_customer_api_v1_customers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_phone_api_v1_customers_by_phone__phone__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                phone: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_customer_api_v1_customers__customer_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_api_v1_sales_quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleQuote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sales_api_v1_sales_get: {
        parameters: {
            query?: {
                q?: string | null;
                start?: string | null;
                end?: string | null;
                status?: components["schemas"]["SaleStatus"] | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SaleSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sale_api_v1_sales_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sale_api_v1_sales__sale_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_return_api_v1_sales__sale_id__returns_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReturnCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleReturnOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoice_pdf_api_v1_sales__sale_id__invoice_pdf_get: {
        parameters: {
            query?: {
                layout?: string;
            };
            header?: never;
            path: {
                sale_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoice_html_api_v1_sales__sale_id__invoice_html_get: {
        parameters: {
            query?: {
                layout?: string;
            };
            header?: never;
            path: {
                sale_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    credit_note_pdf_api_v1_returns__return_id__credit_note_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                return_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_reports_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sales_api_v1_reports_sales_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                group_by?: string;
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    products_api_v1_reports_products_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                limit?: number;
                section?: string;
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_valuation_api_v1_reports_stock_valuation_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    low_stock_api_v1_reports_low_stock_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gst_summary_api_v1_reports_gst_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                section?: string;
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profit_api_v1_reports_profit_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_store_api_v1_settings_store_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreSettingsOut"];
                };
            };
        };
    };
    update_store_api_v1_settings_store_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tax_slabs_api_v1_settings_tax_slabs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxSlabOut"][];
                };
            };
        };
    };
    create_tax_slab_api_v1_settings_tax_slabs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxSlabIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxSlabOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tax_slab_api_v1_settings_tax_slabs__slab_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slab_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxSlabIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxSlabOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tax_slab_api_v1_settings_tax_slabs__slab_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slab_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
